---

- name: Check storage backend
  ansible.builtin.fail:
    msg: Storage backend '{{ duplicacy_autobackup_storage_backend }}' not supported
  when: not duplicacy_autobackup_storage_backend in duplicacy_autobackup_storage_backends

- name: Ensure {{ duplicati_autobackup_script_file_path }}
  ansible.builtin.file:
    path: "{{ duplicati_autobackup_script_file_path }}"
    state: directory
    mode: o-rx

- name: Ensure {{ duplicacy_autobackup_pre_backup_script_file_name }}
  ansible.builtin.template:
    src: pre-backup.sh.j2
    dest: "{{ duplicacy_autobackup_script_file_path }}/{{ duplicacy_autobackup_pre_backup_script_file_name }}"
    mode: ug+x,o-rx
  when: duplicacy_autobackup_pre_backup_script_file_content is defined

- name: Ensure {{ duplicacy_autobackup_post_backup_script_file_name }}
  ansible.builtin.template:
    src: post-backup.sh.j2
    dest: "{{ duplicacy_autobackup_script_file_path }}/{{ duplicacy_autobackup_post_backup_script_file_name }}"
    mode: ug+x,o-rx
  when: duplicacy_autobackup_post_backup_script_file_content is defined

- name: Set _duplicacy_autobackup_container_env_general
  ansible.builtin.set_fact:
    _duplicacy_autobackup_container_env_general:
      BACKUP_NAME: "{{ duplicacy_autobackup_backup_name }}"
      BACKUP_LOCATION: "{{ duplicacy_autobackup_backup_location }}"
      BACKUP_SCHEDULE: "{{ duplicacy_autobackup_backup_schedule }}"
      BACKUP_ENCRYPTION_KEY: "{{ duplicacy_autobackup_backup_encryption_key }}"
      BACKUP_IMMEDIATELY: "{{ duplicacy_autobackup_backup_immediately }}"
      DUPLICACY_INIT_OPTIONS: "{{ duplicacy_autobackup_duplicacy_init_options }}"
      DUPLICACY_BACKUP_OPTIONS: "{{ duplicacy_autobackup_duplicacy_backup_options }}"
      DUPLICACY_PRUNE_OPTIONS: "{{ duplicacy_autobackup_prune_options }}"
      PRUNE_SCHEDULE: "{{ duplicacy_autobackup_prune_schedule }}"

- name: Set _duplicacy_autobackup_container_volumes_general
  ansible.builtin.set_fact:
    _duplicacy_autobackup_container_volumes_general:
      - "{{ duplicacy_autobackup_working_directory }}:/data"
      - "{{ duplicacy_autobackup_repository }}:/repository"
      - "{{ duplicati_autobackup_script_file_path }}/{{ duplicacy_autobackup_pre_backup_script_file_name }}:/scripts/pre-backup.sh"
      - "{{ duplicati_autobackup_script_file_path }}/{{ duplicacy_autobackup_post_backup_script_file_name }}:/scripts/post-backup.sh"

- name: Set fact _duplicacy_autobackup_container_volumes_special
  ansible.builtin.set_fact:
    _duplicacy_autobackup_container_volumes_special: []

- name: Set specials for 'Local disk'
  block:
  - name: Set _duplicacy_autobackup_container_env_special for 'Local disk'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_env_special:
        BACKUP_LOCATION: /backup

  - name: Set _duplicacy_autobackup_container_volumes_special for 'Local disk'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_volumes_special: "{{ _duplicacy_autobackup_container_volumes_special +
        [ duplicacy_autobackup_backup_location+':/backup' ] }}"
  when: duplicacy_autobackup_storage_backend == 'Local disk'

- name: Set specials for 'Blackblaze B2'
  block:
  - name: Set _duplicacy_autobackup_container_env_special for 'Blackblaze B2'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_env_special:
        B2_ID: "{{ duplicacy_autobackup_b2_id }}"
        B2_KEY: "{{ duplicacy_autobackup_b2_key }}"
  when: duplicacy_autobackup_storage_backend == 'Blackblaze B2'

- name: Set specials for 'Onedrive'
  block:
  - name: Set _duplicacy_autobackup_container_env_special for 'Onedrive'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_env_special:
        ONEDRIVE_TOKEN_FILE: "/srv/{{ duplicacy_autobackup_onedrive_token_file_name }}"

  - name: Set _duplicacy_autobackup_container_volumes_special for 'Onedrive'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_volumes_special: "{{ _duplicacy_autobackup_container_volumes_special +
        [ duplicacy_autobackup_secret_file_path+'/'+duplicacy_autobackup_onedrive_token_file_name+':/srv/'+duplicacy_autobackup_onedrive_token_file_name ] }}"

  - name: Set _duplicacy_autobackup_secret_file_name for 'Onedrive'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_secret_file_name: "{{ duplicacy_autobackup_onedrive_token_file_name }}"
  when: duplicacy_autobackup_storage_backend == 'Onedrive'

- name: Set specials for 'SSH/SFTP Keyfile'
  block:
  - name: Set _duplicacy_autobackup_container_env_special for 'SSH/SFTP Keyfile'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_env_special:
        SSH_KEY_FILE: "/srv/{{ duplicacy_autobackup_ssh_key_file_name }}"
        SSH_PASSPHRASE: "{{ duplicacy_autobackup_ssh_passphrase }}"

  - name: Set _duplicacy_autobackup_container_volumes_special for 'SSH/SFTP Keyfile'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_container_volumes_special: "{{ _duplicacy_autobackup_container_volumes_special +
        [ duplicacy_autobackup_secret_file_path+'/'+duplicacy_autobackup_ssh_key_file_name+':/srv/'+duplicacy_autobackup_ssh_key_file_name ] }}"

  - name: Set _duplicacy_autobackup_secret_file_name for 'SSH/SFTP Keyfile'
    ansible.builtin.set_fact:
      _duplicacy_autobackup_secret_file_name: "{{ duplicacy_autobackup_ssh_key_file_name }}"
  when: duplicacy_autobackup_storage_backend == 'SSH/SFTP Keyfile'

- name: Include secret file tasks for 'Onedrive', 'SSH/SFTP Keyfile'
  include_tasks: secret_file.yml
  when: duplicacy_autobackup_storage_backend in ['Onedrive', 'SSH/SFTP Keyfile']

- name: Ensure docker container {{ _duplicacy_autobackup_image }}
  community.docker.docker_container:
    name: "{{ duplicacy_autobackup_container_name }}"
    image: "{{ duplicacy_autobackup_image }}:{{ duplicacy_autobackup_image_tag }}"
    restart_policy: always
    container_default_behavior: compatibility
    env: "{{ _duplicacy_autobackup_container_env_general | combine(_duplicacy_autobackup_container_env_special) }}"
    volumes: "{{ _duplicacy_autobackup_container_volumes_general +_duplicacy_autobackup_container_volumes_special }}"

...
