---

- name: Include secrests file path tasks
  include_tasks: secrets_file_path.yml

- name: Ensure SSH key file
  ansible.builtin.template_file:
    src: id.j2
    dest: "{{ duplicacy_autobackup_token_file_path }}/{{ duplicacy_autobackup_ssh_key_file_name }}"
    mode: o-rx

- name: Ensure docker container {{ _duplicacy_autobackup_image }}
  community.docker.docker_container:
    name: "{{ duplicacy_autobackup_container_name }}"
    image: "{{ _duplicacy_autobackup_image }}"
    restart_policy: always
    container_default_behavior: compatibility
    env:
      BACKUP_NAME: "{{ duplicacy_autobackup_backup_name }}"
      BACKUP_LOCATION: "{{ duplicacy_autobackup_backup_location }}"
      BACKUP_SCHEDULE: "{{ duplicacy_autobackup_backup_schedule }}"
      BACKUP_ENCRYPTION_KEY: "{{ duplicacy_autobackup_backup_encryption_key }}"
      BACKUP_IMMEDIATELY: "{{ duplicacy_autobackup_backup_immediately }}"
      DUPLICACY_INIT_OPTIONS: "{{ duplicacy_autobackup_duplicacy_init_options }}"
      DUPLICACY_PRUNE_OPTIONS: "{{ duplicacy_autobackup_prune_options }}"
      PRUNE_SCHEDULE: "{{ duplicacy_autobackup_prune_schedule }}"
      SSH_KEY_FILE: "/srv/{{ duplicacy_autobackup_ssh_key_file_name }}"
    volumes:
      - "{{ duplicacy_autobackup_working_directory }}:/data"
      - "{{ duplicati_autobackup_script_file_path }}/{{ duplicacy_autobackup_pre_backup_script_file_name }}:/scripts/pre-backup.sh"
      - "{{ duplicati_autobackup_script_file_path }}/{{ duplicacy_autobackup_post_backup_script_file_name }}:/scripts/post-backup.sh"
      - "{{ duplicacy_autobackup_secrets_file_path }}/{{ duplicacy_autobackup_ssh_key_file_name }}:/srv/{{ duplicacy_autobackup_ssh_key_file_name }}"  # noqa line-length

...
